Updated Microsoft.CSharp to 4.5.0 to resolve error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' when downgrading Autofac from 4.8.1 to 4.2.1